# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xgov-hack',
                'doc_host': 'https://AndreasVarotsis.github.io',
                'git_url': 'https://github.com/AndreasVarotsis/xgov-hack',
                'lib_path': 'xgov_hack'},
  'syms': {'xgov_hack.core': {'xgov_hack.core.foo': ('core.html#foo', 'xgov_hack/core.py')}}}
